### ISSUE TITLE
Demo are not working

### ISSUE THREAD

**Issue by SujanKumarK** [onlyurei/knockout-spa#10]
Hi,

I tried to check demo site  http://rentever.com and TodoMVC: https://onlyurei.github.io/todomvc-knockout-spa/
Both are not working. is there any fix?

Sujan

**Comment by SujanKumarK** [comment]
![image](https://cloud.githubusercontent.com/assets/26013182/24049232/6abeb856-0b51-11e7-86a3-b497fcd670f6.png)

**Comment by SujanKumarK** [comment]
![image](https://cloud.githubusercontent.com/assets/26013182/24049725/e6a0256c-0b52-11e7-8212-06bd9025b273.png)

**Comment by onlyurei** [comment]
@SujanKumarK unfortunately GitHub pages seem stopped to support static files referenced under "node_modules" recently. Here's an issue for reference: https://github.com/isaacs/github/issues/844 

Until this is fixed by GitHub, you can checkout the repo of [todomvc-knockout-spa](https://github.com/onlyurei/todomvc-knockout-spa) and try it locally. You'll need a static file server such as [http-server](https://www.npmjs.com/package/http-server) to serve up the root folder of that repo.

**Comment by onlyurei** [comment]
@SujanKumarK solved in https://github.com/onlyurei/todomvc-knockout-spa/commit/830e5019f5066303e415b6ae9a0d558d16b4159d.

The TodoMVC - Knockout SPA GitHub page is working now:
https://onlyurei.github.io/todomvc-knockout-spa/

References:
http://stackoverflow.com/a/43487798/586740
https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3
