### ISSUE TITLE
Inheritance between pages

### ISSUE THREAD

**Issue by paulofoliveira** [onlyurei/knockout-spa#8]
Hi, How can I do inheritance between pages or any similar way using this project?

For instance, I have index.html, but in some pages I need to have a login form or sign in form and another one page with menu on left and content at right. 

Thank you for your help! =)

**Comment by onlyurei** [comment]
@paulofoliveira If the page you are adding conforms to the shared default layout as defined in `index.html`, then all you need to do is populate the `<main>` section, as 
demonstrated by the pages in the bootstrap. 

Otherwise, you can modify `index.html` to suit your specific needs, such as using different page layouts, hide certain common elements on a few pages, etc. 

Things to remember when looking at [`index.html`](https://github.com/onlyurei/knockout-spa/blob/master/index.html):
1. variables referenced with `page.data` are page-specific ones which are defined on page-specific JS files (take a look at the folders except `shared` here: https://github.com/onlyurei/knockout-spa/tree/master/app)
2. variables referenced by name directly are defined on the [`root binding object`](https://github.com/onlyurei/knockout-spa/blob/master/framework/page.js#L71) for the entire app, if you need to modify the page layout, add/hide elements across pages, you can modify [`root-bindings.js`](https://github.com/onlyurei/knockout-spa/blob/master/app/shared/root-bindings.js). Take a look at how the `title` attribute is trying to see if the page has an override function or property also named `title`: https://github.com/onlyurei/knockout-spa/blob/master/app/shared/root-bindings.js#L18

If you can provide a code snippet of what you are trying to achieve, I can probably explain better.

**Comment by paulofoliveira** [comment]
Understood @onlyurei with relationed  the `<main>` section and about `page.data`.  What I would like to do is simliar what I do in ASP.NET MVC that I can inheritance layouts with one Master Page and have other pages that'll have or could have pages.

I have my index.html with the code in <main> similar like this:

```
<main data-bind="template: { name: page.path, data: page.data, afterRender: page.data.afterRender }">
<section id="menu">Here is my Menu</section>
<section id="content">Here is my content page</section>
</main>
```

And my login page:

```
<main data-bind="template: { name: page.path, data: page.data, afterRender: page.data.afterRender }">
<section id="login">
This is my center login box with the fields
</section >
</main>
```

Thus if I have one login page, its structure is different of my actual index.html. Must I create a variable and do binding in sections menu and content or exist an other way do do this? I wouldn't want to copy this internal structure in  index.html with menu to my crud pages for example. Maybe I may have forgotten something.

By the way, it's so good this full-fledged SPA framework shared with the community. Thank you again!

**Comment by onlyurei** [comment]
@paulofoliveira you should not put anything inside the `<main></main>` tags in the provided `index.html` template - the content will be overwritten by knockout once the page binding rendering is done.

What you described sounds to me are just regular pages - you can create the page-specific templates in their respective folders.

**Comment by paulofoliveira** [comment]
Sorry, I expressed wrong. The main tag is empty. In this case I have two templates.  My application pages and login, fac and other pages that doesn't need the menu. What I would like to do is doesn't repeat the all content if possible. For example in my page with menu I would have inheritance (something like that) of index.html in my root folder on the project. Whatever, thank you for you help.
