### ISSUE TITLE
[Widget Form Input] filled is true if value is null; [Widget Form] deletes empty input values in serialize.

### ISSUE THREAD

**Issue by Billybob** [onlyurei/knockout-spa#9]
Hi, when i send a null value to the widget.form.form-input.js ( new Input("name", null, false) )
this.filled is true !

```
this.filled = ko.computed(function () {
    if(this.value() === null){
        return false;
    }
    return !!('' + this.value()).compact();
}.bind(this));
```

**Comment by onlyurei** [comment]
@Billybob Thanks for the report and the proposed fix! 
Indeed, because `'' + null` => `'null'` is truthy, so `!!'null' === true` is true.
Instead of passing `null` as the initial value, you can pass `''` empty string or `undefined`.

Looking at `this.value = ko.isObservable(value) ? value : ko.observable(Object.isFunction(value) ? value() : ((value !== undefined) ? value : ''));` (https://github.com/onlyurei/knockout-spa/blob/master/widget/form/form-input.js#L7), looks like `value` is checked explicitly with `undefined` (instead of `value != undefined`, which will return `false` for `null` and defaulting to `''`). I don't remember the initial design thoughts why it's implemented this way (wrote and used the `form` widget classes over 1.5 years ago), but I have a vague impression that this might solve some edge use cases.

What do you think?

BTW if you are interested in my use cases of the `form` widgets, checkout http://rentever.com. All the form fields (including the filters/sorters/location checkbox/sliders) use them.

**Comment by Billybob** [comment]
It's the server (python/Django) that provides the initial value `null`
https://docs.djangoproject.com/en/1.10/ref/models/fields/#null
http://stackoverflow.com/questions/11351619/how-to-make-djangos-datetimefield-optional

I can change this by `''` but in my case it's easier to manage this in form-input.js file, because I should manage the receipt and sending of the value 'null'.

NB: serialize function (form.js) delete fields with `null` value :worried: 

http://rentever.com very good :+1:

**Comment by onlyurei** [comment]
@Billybob make sense in your use case and I think this behavior should be expected for most cases. Making the change as you proposed.

Regarding the empty values (`undefined`, `null`, `''`) being deleted, I'm adding a `keepEmptyValues` param in `serialize` method of the `Form` class to cater this use case. I think my original intention was to keep the url clean (by removing query strings with empty values), and avoid `null` and `undefined` to be deserialized as strings in the backend api.
